# Generated by Django 5.0.1 on 2024-01-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_order_id_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
