# Generated by Django 5.0.1 on 2024-01-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_type_product_comments_order_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Canteen', 'Canteen'), ('Cleaning', 'Cleaning'), ('Food', 'Food'), ('Medical Item', 'Medical Item'), ('Saftey Item', 'Saftey Item')], max_length=50, null=True),
        ),
    ]
