# Generated by Django 5.0.1 on 2024-01-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Supplier',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
