# Generated by Django 5.0.1 on 2024-01-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=255)),
                ('invoice_no', models.CharField(max_length=255, unique=True)),
                ('pdf_file', models.FileField(upload_to='invoice_pdfs/')),
            ],
        ),
    ]
