# Generated by Django 5.0.1 on 2024-01-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
