# Generated by Django 5.0.1 on 2024-01-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_invoice_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='datetime',
        ),
        migrations.AddField(
            model_name='invoice',
            name='month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
